# Disable the blank line at the start of the prompt
format = '$time$all'
add_newline = false

[character]
success_symbol = '[â¯](bold green)'
error_symbol = '[â¯](bold red)'

[directory]
truncation_length = 10
truncate_to_repo = false
repo_root_style  = 'underline bold purple'

[time]
disabled = false
format = "ğŸ•™ [\\[ $time \\]]($style) \n"
time_format = '%T'
